import a51 from './../images/items/a51.jpg'
import ipro11 from './../images/items/ipro11.jpg'
import s10 from './../images/items/s10.jpg'
import s10p from './../images/items/s10p.jpg'
import xr6p from './../images/items/xr6p.jpg'
import lp2 from './../images/items/lp2.jpg'
import i8p from './../images/items/i8p.jpg'
import i7p from './../images/items/i7p.jpg'
import a71 from './../images/items/a71.jpg'
import ix from './../images/items/ix.jpg'
import i6s from './../images/items/i6s.jpg'
import sonyl3 from './../images/items/sonyl3.jpg'
import la6 from './../images/items/la6.jpg'
import lk6n from './../images/items/lk6n.jpg'
import lk6p from './../images/items/lk6p.jpg'
import lvs1 from './../images/items/lvs1.jpg'
import sxa2 from './../images/items/sxa2.jpg'
import sxa2u from './../images/items/sxa2u.jpg'
import sxl2 from './../images/items/sxl2.jpg'
import sxa1 from './../images/items/sxa1.jpg'
import sxl1 from './../images/items/sxl1.jpg'
import sxx from './../images/items/sxx.jpg'
import sxe5 from './../images/items/sxe5.jpg'
import xr6np from './../images/items/xrn6p.jpg'
import xma2 from './../images/items/xma2.jpg'
import xm8 from './../images/items/xm8.jpg'
import xpf1 from './../images/items/xpf1.jpg'
import xrg from './../images/items/xrg.jpg'
import xmm3 from './../images/items/xmm3.jpg'
import xr7 from './../images/items/xr7.jpg'
import xm9 from './../images/items/xm9.jpg'
import xr7a from './../images/items/xr7a.jpg'
import xm9t from './../images/items/xm9t.jpg'
import xrn8 from './../images/items/xrn8.jpg'
import xr8 from './../images/items/xr8.jpg'
import ixs from './../images/items/ixs.jpg'
import ixr from './../images/items/ixr.jpg'
import i11pm from './../images/items/i11pm.jpg'
import i11 from './../images/items/i11.jpg'
import i8 from './../images/items/i8.jpg'
import ise from './../images/items/ise.jpg'
import i7 from './../images/items/i7.jpg'
import sgs20p from './../images/items/sgs20p.jpg'
import sgs20u from './../images/items/sgs20u.jpg'
import sgs20 from './../images/items/sgs20.jpg'
import sgs10l from './../images/items/sgs10l.jpg'
import sgn10l from './../images/items/sgn10l.jpg'
import a01 from './../images/items/a01.jpg'
import a31 from './../images/items/a31.jpg'
import a21s from './../images/items/a21s.jpg'
import a11 from './../images/items/a11.jpg'
import a41 from './../images/items/a41.jpg'
import sz from './../images/items/sz.jpg'
import sgn10 from './../images/items/sgn10.jpg'
import a20 from './../images/items/a20.jpg'
import a50 from './../images/items/a50.jpg'
import a30 from './../images/items/a30.jpg'
import a40 from './../images/items/a40.jpg'


const phones = [
    {
        id: 1,
        name: 'Samsung Galaxy A51',
        brand: 'Samsung',
        price: 290,
        photo: a51,
        ram: '4GB',
        memory: '64GB',
        year: 2020,
        os: 'Android',
        osv: 'Android 10.0',
        fCamera: '32MP',
        mCamera: '48MP + 12MP + 5MP + 5MP',
        screen: '6.5 inch',
        battery: '4000 mAh',
        weight: '172 g'
    },
    {
        id: 2,
        name: 'iPhone 11 Pro',
        brand: 'Apple',
        price: 1270,
        photo: ipro11,
        ram: '4GB',
        memory: '64GB',
        year: 2019,
        os: 'iOS',
        osv: 'iOS 13',
        fCamera: '12MP',
        mCamera: '12MP + 12MP + 12MP',
        screen: '5.8 inch',
        battery: '3190 mAh',
        weight: '188 g'
    },
    {
        id: 3,
        name: 'Samsung Galaxy S10',
        brand: 'Samsung',
        price: 590,
        photo: s10,
        ram: '8GB',
        memory: '128GB',
        year: 2019,
        os: 'Android',
        osv: 'Android 9.0 (Pie)',
        fCamera: '10MP',
        mCamera: '16MP + 12MP + 12MP',
        screen: '6.1 inch',
        battery: '3400 mAh',
        weight: '157 g'
    },
    {
        id: 4,
        name: 'Samsung Galaxy S10 Plus',
        brand: 'Samsung',
        price: 730,
        photo: s10p,
        ram: '8GB',
        memory: '128GB',
        year: 2019,
        os: 'Android',
        osv: 'Android 9.0 (Pie)',
        fCamera: '10MP + 8MP',
        mCamera: '16MP + 12MP + 12MP',
        screen: '6.5 inch',
        battery: '4000 mAh',
        weight: '172 g'
    },
    {
        id: 5,
        name: 'Xiaomi Redmi Note 6 Pro 3',
        brand: 'Xiaomi',
        price: 150,
        photo: xr6p,
        ram: '3GB',
        memory: '32GB',
        year: 2018,
        os: 'Android',
        osv: 'Android 8.1',
        fCamera: '20MP',
        mCamera: '12MP + 5MP',
        screen: '6.2 inch',
        battery: '4000 mAh',
        weight: '182 g'
    },
    {
        id: 6,
        name: 'Lenovo P2',
        brand: 'Lenovo',
        price: 166,
        photo: lp2,
        ram: '4GB',
        memory: '32GB',
        year: 2016,
        os: 'Android',
        osv: 'Android 6.0',
        fCamera: '5MP',
        mCamera: '12MP',
        screen: '5.5 inch',
        battery: '5100 mAh',
        weight: '177 g'
    },
    {
        id: 7,
        name: 'Apple iPhone 8 Plus',
        brand: 'Apple',
        price: 670,
        photo: i8p,
        ram: '3GB',
        memory: '64GB',
        year: 2018,
        os: 'iOS',
        osv: 'iOS 11',
        fCamera: '7MP',
        mCamera: '12MP + 12MP',
        screen: '5.5 inch',
        battery: '2691 mAh',
        weight: '202 g'
    },
    {
        id: 8,
        name: 'Apple iPhone 7 Plus',
        brand: 'Apple',
        price: 525,
        photo: i7p,
        ram: '3GB',
        memory: '32GB',
        year: 2016,
        os: 'iOS',
        osv: 'iOS 9',
        fCamera: '7MP',
        mCamera: '12MP + 12MP',
        screen: '5.5 inch',
        battery: '2900 mAh',
        weight: '188 g'
    },
    {
        id: 9,
        name: 'Samsung Galaxy A71',
        brand: 'Samsung',
        price: 399,
        photo: a71,
        ram: '6GB',
        memory: '128GB',
        year: 2020,
        os: 'Android',
        osv: 'Android 10.0',
        fCamera: '32MP',
        mCamera: '64MP + 12MP + 5MP + 5MP',
        screen: '6.7 inch',
        battery: '4500 mAh',
        weight: '179 g'
    },
    {
        id: 10,
        name: 'Apple iPhone X',
        brand: 'Apple',
        price: 780,
        photo: ix,
        ram: '4GB',
        memory: '128GB',
        year: 2017,
        os: 'iOS',
        osv: 'iOS 10',
        fCamera: '7MP',
        mCamera: '12MP + 12MP',
        screen: '6.2 inch',
        battery: '2716 mAh',
        weight: '174 g'
    },
    {
        id: 11,
        name: 'Apple iPhone 6S',
        brand: 'Apple',
        price: 280,
        photo: i6s,
        ram: '2GB',
        memory: '32GB',
        year: 2016,
        os: 'iOS',
        osv: 'iOS 8',
        fCamera: '5MP',
        mCamera: '12MP',
        screen: '4.7 inch',
        battery: '1715 mAh',
        weight: '143 g'
    },
    {
        id: 12,
        name: 'Sony Xperia L3',
        brand: 'Sony',
        price: 136,
        photo: sonyl3,
        ram: '3GB',
        memory: '32GB',
        year: 2019,
        os: 'Android',
        osv: 'Android 8.0',
        fCamera: '5MP',
        mCamera: '13MP',
        screen: '5.7 inch',
        battery: '3300 mAh',
        weight: '156 g'
    },
    {
        id: 13,
        name: 'Apple iPhone Xs',
        brand: 'Apple',
        price: 1020,
        photo: ixs,
        ram: '4GB',
        memory: '128GB',
        year: 2018,
        os: 'iOS',
        osv: 'iOS 13',
        fCamera: '7MP',
        mCamera: '12MP + 12MP',
        screen: '6.3 inch',
        battery: '2816 mAh',
        weight: '184 g'
    },
    {
        id: 14,
        name: 'Apple iPhone Xs Max',
        brand: 'Apple',
        price: 1220,
        photo: ixs,
        ram: '6GB',
        memory: '128GB',
        year: 2018,
        os: 'iOS',
        osv: 'iOS 13',
        fCamera: '7MP',
        mCamera: '12MP + 12MP',
        screen: '6.5 inch',
        battery: '2916 mAh',
        weight: '186 g'
    },
    {
        id: 15,
        name: 'Apple iPhone XR',
        brand: 'Apple',
        price: 760,
        photo: ixr,
        ram: '3GB',
        memory: '64GB',
        year: 2018,
        os: 'iOS',
        osv: 'iOS 13',
        fCamera: '7MP',
        mCamera: '12MP',
        screen: '6.1 inch',
        battery: '1916 mAh',
        weight: '194 g'
    },
    {
        id: 16,
        name: 'iPhone 11 Pro Max',
        brand: 'Apple',
        price: 1350,
        photo: i11pm,
        ram: '4GB',
        memory: '64GB',
        year: 2019,
        os: 'iOS',
        osv: 'iOS 13',
        fCamera: '12MP',
        mCamera: '12MP + 12MP + 12MP',
        screen: '6.5 inch',
        battery: '3969 mAh',
        weight: '226 g'
    },
    {
        id: 17,
        name: 'iPhone 11',
        brand: 'Apple',
        price: 960,
        photo: i11,
        ram: '4GB',
        memory: '128GB',
        year: 2019,
        os: 'iOS',
        osv: 'iOS 13',
        fCamera: '12MP',
        mCamera: '12MP + 12MP',
        screen: '6.1 inch',
        battery: '3046 mAh',
        weight: '194 g'
    },
    {
        id: 18,
        name: 'Apple iPhone 8',
        brand: 'Apple',
        price: 650,
        photo: i8,
        ram: '2GB',
        memory: '128GB',
        year: 2017,
        os: 'iOS',
        osv: 'iOS 13',
        fCamera: '7MP',
        mCamera: '12MP',
        screen: '4.7 inch',
        battery: '1821 mAh',
        weight: '148 g'
    },
    {
        id: 19,
        name: 'Xiaomi Redmi Note 6 PRO',
        brand: 'Xiaomi',
        price: 160,
        photo: xr6np,
        ram: '4GB',
        memory: '64GB',
        year: 2018,
        os: 'Android',
        osv: 'Android 8.1',
        fCamera: '20MP + 5MP',
        mCamera: '12MP + 5MP',
        screen: '6.2 inch',
        battery: '4000 mAh',
        weight: '182 g'
    },
    {
        id: 20,
        name: 'Xiaomi Mi A2',
        brand: 'Xiaomi',
        price: 140,
        photo: xma2,
        ram: '4GB',
        memory: '32GB',
        year: 2018,
        os: 'Android',
        osv: 'Android 8.1',
        fCamera: '20MP',
        mCamera: '12MP + 20MP',
        screen: '5.99 inch',
        battery: '3010 mAh',
        weight: '166 g'
    },
    {
        id: 21,
        name: 'Xiaomi Mi 8',
        brand: 'Xiaomi',
        price: 220,
        photo: xm8,
        ram: '6GB',
        memory: '64GB',
        year: 2018,
        os: 'Android',
        osv: 'Android 8.1',
        fCamera: '20MP',
        mCamera: '12MP + 12MP',
        screen: '6.2 inch',
        battery: '3400 mAh',
        weight: '175 g'
    },
    {
        id: 22,
        name: 'Samsung Galaxy S20+',
        brand: 'Samsung',
        price: 990,
        photo: sgs20p,
        ram: '8GB',
        memory: '128GB',
        year: 2020,
        os: 'Android',
        osv: 'Android 10.0',
        fCamera: '10MP',
        mCamera: '12MP + 64MP + 12MP + 3D(ToF)',
        screen: '6.7 inch',
        battery: '4500 mAh',
        weight: '186 g'
    },
    {
        id: 23,
        name: 'Samsung Galaxy S20 Ultra',
        brand: 'Samsung',
        price: 1200,
        photo: sgs20u,
        ram: '12GB',
        memory: '128GB',
        year: 2020,
        os: 'Android',
        osv: 'Android 10.0',
        fCamera: '40MP',
        mCamera: '12MP + 108MP + 48MP + 3D(ToF)',
        screen: '6.9 inch',
        battery: '5000 mAh',
        weight: '220 g'
    },
    {
        id: 24,
        name: 'Samsung Galaxy S20',
        brand: 'Samsung',
        price: 900,
        photo: sgs20,
        ram: '8GB',
        memory: '128GB',
        year: 2020,
        os: 'Android',
        osv: 'Android 10.0',
        fCamera: '10MP',
        mCamera: '12MP + 64MP + 12MP',
        screen: '6.2 inch',
        battery: '4000 mAh',
        weight: '163 g'
    },
    {
        id: 25,
        name: 'Samsung Galaxy S10 Lite',
        brand: 'Samsung',
        price: 700,
        photo: sgs10l,
        ram: '6GB',
        memory: '128GB',
        year: 2020,
        os: 'Android',
        osv: 'Android 10.0',
        fCamera: '32MP',
        mCamera: '48MP + 12MP + 5MP',
        screen: '6.7 inch',
        battery: '4500 mAh',
        weight: '186 g'
    },
    {
        id: 26,
        name: 'Xiaomi Pocophone F1',
        brand: 'Xiaomi',
        price: 230,
        photo: xpf1,
        ram: '6GB',
        memory: '64GB',
        year: 2018,
        os: 'Android',
        osv: 'Android 8.1',
        fCamera: '20MP',
        mCamera: '12MP + 5MP',
        screen: '6.18 inch',
        battery: '4000 mAh',
        weight: '182 g'
    },
    {
        id: 27,
        name: 'Xiaomi Redmi Go',
        brand: 'Xiaomi',
        price: 65,
        photo: xrg,
        ram: '1GB',
        memory: '8GB',
        year: 2019,
        os: 'Android',
        osv: 'Android 8.1',
        fCamera: '8MP',
        mCamera: '5MP',
        screen: '5.0 inch',
        battery: '3000 mAh',
        weight: '137 g'
    },
    {
        id: 28,
        name: 'iPhone SE',
        brand: 'Apple',
        price: 600,
        photo: ise,
        ram: '3GB',
        memory: '128GB',
        year: 2020,
        os: 'iOS',
        osv: 'iOS 13',
        fCamera: '7MP',
        mCamera: '12MP',
        screen: '4.7 inch',
        battery: '1821 mAh',
        weight: '148 g'
    },
    {
        id: 29,
        name: 'Apple iPhone 7',
        brand: 'Apple',
        price: 550,
        photo: i7,
        ram: '2GB',
        memory: '128GB',
        year: 2016,
        os: 'iOS',
        osv: 'iOS 11',
        fCamera: '7MP',
        mCamera: '12MP',
        screen: '4.7 inch',
        battery: '1960 mAh',
        weight: '138 g'
    },
    {
        id: 30,
        name: 'Xiaomi Mi Mix 3',
        brand: 'Xiaomi',
        price: 299,
        photo: xmm3,
        ram: '6GB',
        memory: '128GB',
        year: 2018,
        os: 'Android',
        osv: 'Android 9.0 (Pie)',
        fCamera: '24MP + 2MP',
        mCamera: '12MP + 12MP',
        screen: '6.3 inch',
        battery: '3200 mAh',
        weight: '218 g'
    },
    {
        id: 31,
        name: 'Samsung Galaxy Note 10 Lite',
        brand: 'Samsung',
        price: 650,
        photo: sgn10l,
        ram: '6GB',
        memory: '128GB',
        year: 2020,
        os: 'Android',
        osv: 'Android 10.0',
        fCamera: '32MP',
        mCamera: '12MP + 12MP + 12MP',
        screen: '6.7 inch',
        battery: '4500 mAh',
        weight: '199 g'
    },
    {
        id: 32,
        name: 'Xiaomi Redmi 7',
        brand: 'Xiaomi',
        price: 120,
        photo: xr7,
        ram: '3GB',
        memory: '32GB',
        year: 2019,
        os: 'Android',
        osv: 'Android 9.0 (Pie)',
        fCamera: '8MP',
        mCamera: '12MP + 2MP',
        screen: '6.2 inch',
        battery: '4000 mAh',
        weight: '180 g'
    },
    {
        id: 33,
        name: 'Samsung Galaxy A01',
        brand: 'Samsung',
        price: 99,
        photo: a01,
        ram: '2GB',
        memory: '16GB',
        year: 2020,
        os: 'Android',
        osv: 'Android 10.0',
        fCamera: '5MP',
        mCamera: '13MP + 2MP',
        screen: '5.7 inch',
        battery: '3000 mAh',
        weight: '149 g'
    },
    {
        id: 34,
        name: 'Samsung Galaxy A31',
        brand: 'Samsung',
        price: 250,
        photo: a31,
        ram: '4GB',
        memory: '128GB',
        year: 2020,
        os: 'Android',
        osv: 'Android 10.0',
        fCamera: '20MP',
        mCamera: '48MP + 8MP + 5MP + 5MP',
        screen: '6.4 inch',
        battery: '5000 mAh',
        weight: '185 g'
    },
    {
        id: 35,
        name: 'Xiaomi Redmi Note 7',
        brand: 'Xiaomi',
        price: 180,
        photo: xr7,
        ram: '4GB',
        memory: '128GB',
        year: 2019,
        os: 'Android',
        osv: 'Android 9.0 (Pie)',
        fCamera: '13MP',
        mCamera: '48MP + 5MP',
        screen: '6.3 inch',
        battery: '4000 mAh',
        weight: '186 g'
    },
    {
        id: 36,
        name: 'Samsung Galaxy A21s',
        brand: 'Samsung',
        price: 210,
        photo: a21s,
        ram: '3GB',
        memory: '32GB',
        year: 2020,
        os: 'Android',
        osv: 'Android 10.0',
        fCamera: '13MP',
        mCamera: '48MP + 8MP + 2MP + 2MP',
        screen: '6.5 inch',
        battery: '5000 mAh',
        weight: '192 g'
    },
    {
        id: 37,
        name: 'Samsung Galaxy A11',
        brand: 'Samsung',
        price: 180,
        photo: a11,
        ram: '2GB',
        memory: '32GB',
        year: 2020,
        os: 'Android',
        osv: 'Android 10.0',
        fCamera: '8MP',
        mCamera: '13MP + 8MP + 5MP',
        screen: '6.4 inch',
        battery: '4000 mAh',
        weight: '177 g'
    },
    {
        id: 38,
        name: 'Samsung Galaxy A41',
        brand: 'Samsung',
        price: 320,
        photo: a41,
        ram: '4GB',
        memory: '64GB',
        year: 2020,
        os: 'Android',
        osv: 'Android 10.0',
        fCamera: '25MP',
        mCamera: '48MP + 8MP + 5MP',
        screen: '6.1 inch',
        battery: '3500 mAh',
        weight: '152 g'
    },
    {
        id: 39,
        name: 'Samsung Galaxy A10',
        brand: 'Samsung',
        price: 150,
        photo: sz,
        ram: '2GB',
        memory: '32GB',
        year: 2019,
        os: 'Android',
        osv: 'Android 9.0 (Pie)',
        fCamera: '5MP',
        mCamera: '13MP',
        screen: '6.2 inch',
        battery: '3400 mAh',
        weight: '168 g'
    },
    {
        id: 40,
        name: 'Samsung Galaxy Note 10',
        brand: 'Samsung',
        price: 950,
        photo: sgn10,
        ram: '8GB',
        memory: '256GB',
        year: 2019,
        os: 'Android',
        osv: 'Android 9.0 (Pie)',
        fCamera: '10MP',
        mCamera: '16MP + 12MP + 12MP',
        screen: '6.3 inch',
        battery: '3500 mAh',
        weight: '168 g'
    },
    {
        id: 41,
        name: 'Sony Xperia XA2 Plus',
        brand: 'Sony',
        price: 196,
        photo: sxa2,
        ram: '4GB',
        memory: '32GB',
        year: 2018,
        os: 'Android',
        osv: 'Android 8.0',
        fCamera: '8MP',
        mCamera: '23MP',
        screen: '6.0 inch',
        battery: '3580 mAh',
        weight: '204 g'
    },
    {
        id: 42,
        name: 'Sony Xperia XA2 Ultra Dual',
        brand: 'Sony',
        price: 188,
        photo: sxa2u,
        ram: '4GB',
        memory: '32GB',
        year: 2018,
        os: 'Android',
        osv: 'Android 8.0',
        fCamera: '16MP + 8MP',
        mCamera: '23MP',
        screen: '6.0 inch',
        battery: '3580 mAh',
        weight: '221 g'
    },
    {
        id: 43,
        name: 'Samsung Galaxy A50',
        brand: 'Samsung',
        price: 250,
        photo: a50,
        ram: '4GB',
        memory: '64GB',
        year: 2019,
        os: 'Android',
        osv: 'Android 9.0 (Pie)',
        fCamera: '25MP',
        mCamera: '25MP + 5MP + 8MP',
        screen: '6.4 inch',
        battery: '4000 mAh',
        weight: '166 g'
    },
    {
        id: 44,
        name: 'Samsung Galaxy A20',
        brand: 'Samsung',
        price: 190,
        photo: a20,
        ram: '3GB',
        memory: '32GB',
        year: 2019,
        os: 'Android',
        osv: 'Android 9.0 (Pie)',
        fCamera: '8MP',
        mCamera: '13MP + 5MP',
        screen: '6.4 inch',
        battery: '4000 mAh',
        weight: '169 g'
    },
    {
        id: 45,
        name: 'Samsung Galaxy A30',
        brand: 'Samsung',
        price: 199,
        photo: a30,
        ram: '3GB',
        memory: '32GB',
        year: 2019,
        os: 'Android',
        osv: 'Android 9.0 (Pie)',
        fCamera: '16MP',
        mCamera: '16MP + 5MP',
        screen: '6.4 inch',
        battery: '4000 mAh',
        weight: '165 g'
    },
    {
        id: 46,
        name: 'Samsung Galaxy A40',
        brand: 'Samsung',
        price: 249,
        photo: a40,
        ram: '4GB',
        memory: '64GB',
        year: 2019,
        os: 'Android',
        osv: 'Android 9.0 (Pie)',
        fCamera: '25MP',
        mCamera: '16MP + 5MP',
        screen: '5.99 inch',
        battery: '3100 mAh',
        weight: '140 g'
    },
    {
        id: 47,
        name: 'Xiaomi Mi 9',
        brand: 'Xiaomi',
        price: 250,
        photo: xm9,
        ram: '6GB',
        memory: '128GB',
        year: 2019,
        os: 'Android',
        osv: 'Android 9.0 (Pie)',
        fCamera: '20MP',
        mCamera: '48MP + 12MP + 16MP',
        screen: '5.99 inch',
        battery: '3300 mAh',
        weight: '173 g'
    },
    {
        id: 48,
        name: 'Xiaomi Redmi 7A',
        brand: 'Xiaomi',
        price: 150,
        photo: xr7a,
        ram: '2GB',
        memory: '16GB',
        year: 2019,
        os: 'Android',
        osv: 'Android 9.0 (Pie)',
        fCamera: '5MP',
        mCamera: '13MP + 12MP',
        screen: '5.45 inch',
        battery: '4000 mAh',
        weight: '165 g'
    },
    {
        id: 49,
        name: 'Lenovo A6010 Pro',
        brand: 'Lenovo',
        price: 85,
        photo: la6,
        ram: '2GB',
        memory: '16GB',
        year: 2015,
        os: 'Android',
        osv: 'Android 5.0',
        fCamera: '5MP',
        mCamera: '13MP',
        screen: '5.5 inch',
        battery: '2300 mAh',
        weight: '128 g'
    },
    {
        id: 50,
        name: 'Lenovo K6 Note',
        brand: 'Lenovo',
        price: 126,
        photo: lk6n,
        ram: '3GB',
        memory: '32GB',
        year: 2016,
        os: 'Android',
        osv: 'Android 6.0',
        fCamera: '8MP',
        mCamera: '16MP',
        screen: '5.5 inch',
        battery: '4000 mAh',
        weight: '169 g'
    },
    {
        id: 51,
        name: 'Sony Xperia E5',
        brand: 'Sony',
        price: 48,
        photo: sxe5,
        ram: '2GB',
        memory: '16GB',
        year: 2016,
        os: 'Android',
        osv: 'Android 6.0',
        fCamera: '5MP',
        mCamera: '13MP',
        screen: '5.0 inch',
        battery: '2300 mAh',
        weight: '147 g'
    },
    {
        id: 52,
        name: 'Sony Xperia X',
        brand: 'Sony',
        price: 110,
        photo: sxx,
        ram: '3GB',
        memory: '64GB',
        year: 2016,
        os: 'Android',
        osv: 'Android 6.0',
        fCamera: '13MP',
        mCamera: '23MP',
        screen: '5.0 inch',
        battery: '2620 mAh',
        weight: '153 g'
    },
    {
        id: 53,
        name: 'Xiaomi Mi 9T',
        brand: 'Xiaomi',
        price: 245,
        photo: xm9t,
        ram: '6GB',
        memory: '64GB',
        year: 2019,
        os: 'Android',
        osv: 'Android 9.0 (Pie)',
        fCamera: '20MP',
        mCamera: '48MP + 8MP + 13MP',
        screen: '6.3 inch',
        battery: '4000 mAh',
        weight: '191 g'
    },
    {
        id: 54,
        name: 'Lenovo K6 Power',
        brand: 'Lenovo',
        price: 98,
        photo: lk6p,
        ram: '2GB',
        memory: '16GB',
        year: 2016,
        os: 'Android',
        osv: 'Android 6.0',
        fCamera: '8MP',
        mCamera: '13MP',
        screen: '5.0 inch',
        battery: '4000 mAh',
        weight: '145 g'
    },
    {
        id: 55,
        name: 'Sony Xperia L2',
        brand: 'Sony',
        price: 109,
        photo: sxl2,
        ram: '3GB',
        memory: '32GB',
        year: 2018,
        os: 'Android',
        osv: 'Android 8.0',
        fCamera: '8MP',
        mCamera: '13MP',
        screen: '5.5 inch',
        battery: '3300 mAh',
        weight: '178 g'
    },
    {
        id: 56,
        name: 'Lenovo Vibe S1',
        brand: 'Lenovo',
        price: 126,
        photo: lvs1,
        ram: '3GB',
        memory: '32GB',
        year: 2015,
        os: 'Android',
        osv: 'Android 5.0',
        fCamera: '8MP + 2MP',
        mCamera: '13MP',
        screen: '5.0 inch',
        battery: '2420 mAh',
        weight: '132 g'
    },
    {
        id: 57,
        name: 'Xiaomi Redmi Note 8',
        brand: 'Xiaomi',
        price: 190,
        photo: xrn8,
        ram: '4GB',
        memory: '64GB',
        year: 2019,
        os: 'Android',
        osv: 'Android 9.0 (Pie)',
        fCamera: '13MP',
        mCamera: '48MP + 8MP + 2MP + 2MP',
        screen: '6.3 inch',
        battery: '4000 mAh',
        weight: '190 g'
    },
    {
        id: 58,
        name: 'Xiaomi Redmi 8A',
        brand: 'Xiaomi',
        price: 110,
        photo: xr8,
        ram: '2GB',
        memory: '32GB',
        year: 2019,
        os: 'Android',
        osv: 'Android 9.0 (Pie)',
        fCamera: '8MP',
        mCamera: '12MP',
        screen: '6.2 inch',
        battery: '5000 mAh',
        weight: '188 g'
    },
    {
        id: 59,
        name: 'Sony Xperia XA1',
        brand: 'Sony',
        price: 99,
        photo: sxa1,
        ram: '3GB',
        memory: '32GB',
        year: 2017,
        os: 'Android',
        osv: 'Android 7.0',
        fCamera: '8MP',
        mCamera: '23MP',
        screen: '5.0 inch',
        battery: '2300 mAh',
        weight: '143 g'
    },
    {
        id: 60,
        name: 'Sony Xperia L1 Dual',
        brand: 'Sony',
        price: 78,
        photo: sxl1,
        ram: '2GB',
        memory: '16GB',
        year: 2017,
        os: 'Android',
        osv: 'Android 7.0',
        fCamera: '5MP',
        mCamera: '13MP',
        screen: '5.5 inch',
        battery: '2620 mAh',
        weight: '180 g'
    }
]

export default phones